### PR TITLE
Add support for quantized qwen2-0.5b

### PR DESCRIPTION
**Pull request by bil-ash**
This PR adds support for quantized(q4f16_1) qwen2-0.5b. Solves [issue](https://github.com/mlc-ai/web-llm-chat/issues/41l) . [PR](https://github.com/mlc-ai/web-llm/pull/490) must be merged before merging this. 
@Neet-Nestor

### CODE REVIEW

**Comment by Neet-Nestor** [comment]
Unfortunately, this won't fix the issue since the model `Qwen2-0.5B-Instruct-q4f16-MLC` you added is not available in [WebLLM](https://github.com/mlc-ai/web-llm/blob/main/src/config.ts#L618) yet. Instead we need to compile the model, upload to huggingface, update WebLLM, and finally update our app.

**Comment by bil-ash** [comment]
> Unfortunately, this won't fix the issue since the model `Qwen2-0.5B-Instruct-q4f16-MLC` you added is not available in [WebLLM](https://github.com/mlc-ai/web-llm/blob/main/src/config.ts#L618) yet. Instead we need to compile the model, upload to huggingface, update WebLLM, and finally update our app.

I saw that and so I have also created the required [PR](https://github.com/mlc-ai/web-llm/pull/490) in the web-llm repo.

**Comment by Neet-Nestor** [comment]
Thanks! Let me try

**Comment by Neet-Nestor** [comment]
Thanks! It's working perfectly on my end. I will leave the other 2 PRs for my team to review, but I can merge this one and publish a new version of the webapp so that you can use it immediately.

**Review by Neet-Nestor — APPROVED** [review]

**Pull request merged**
